### ISSUE TITLE
Figma add [teamurl] doesn't seem to work

### ISSUE THREAD

**Issue by davidmfay** [jonrohan/alfred-figma#4]
So excited to use this! There might be an issue with the last step: It looks like anything written after the `add` part of the command will initiate a Google search instead of adding team.

(Also, any hints on where to find the team url? I'm not sure where to grab this from, and I'm sure other folks will have the same question.)

![image](https://user-images.githubusercontent.com/3246966/47583166-72482b00-d90b-11e8-9e3c-41deae49b6a1.png)
 
![image](https://user-images.githubusercontent.com/3246966/47583183-7f651a00-d90b-11e8-9edb-ae0a88e94ce1.png)

**Comment by jonrohan** [comment]
Glad the workflow has been so well received. 

You can find your figma team url by visiting the website in your web browser and clicking on the team logo in the left hand column. It should look something like this `https://www.figma.com/files/team/12345567789/CoolTeam`. The workflow uses regular expressions to try and find the ID `12345567789` and the Name `CoolTeam`. Assuming your `FIGMA_TOKEN` was  setup correctly in your https://www.alfredapp.com/help/workflows/advanced/variables/ Workflow's environment variables, it will start searching the API and caching those results for 1 day.

**Comment by davidmfay** [comment]
Ah, thanks so much - I wasn't sure what the teamURL was, but your response cleared that up. Cheers!
